# Introduction to Scikit-Learn (sklearn)

I'll be trying to learn and implement some of the most useful features of the Scikit-Learn library in this notebook.

What we're going to cover:

An end-to-end Scikit-Learn workflow
1. [Getting the data ready](#section_1)
2. [Choose the right estimator/algorithm for our problems](#section_2)
3. [Fit the model/algorithm and use it to make predictions on our data](#section_3)
4. [Evaluating a model](#section_4)
5. [Improve a model](#section_5)
6. [Save and load a trained model](#section_6)
7. [Putting it all together!](#section_7)


In [9]:
# standard imports
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline

### 1. Getting Data Ready


In [10]:
# get data ready

heart_disease = pd.read_csv("data/heart-disease.csv")
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [11]:
# create x (features matrix)
x = heart_disease.drop("target", axis=1)

# create y (labels)
y = heart_disease["target"]

<a id='section_2'></a>
### 2. Choosing the right estimator/algorithm for our problems

In [12]:
# choose the right model and hyperparameters
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()
# tested below. n_estimators=40 came out best
# clf = RandomForestClassifier(n_estimators=40)

# we'll keep the default hyperparameters
clf.get_params()


{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [13]:
# you can ignore the warnings

import sklearn
sklearn.show_versions()


System:
    python: 3.10.13 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:24:38) [MSC v.1916 64 bit (AMD64)]
executable: c:\Users\mcruz\ztm_ml_projects\sklearn-intro\env\python.exe
   machine: Windows-10-10.0.19045-SP0

Python dependencies:
      sklearn: 1.3.0
          pip: 23.2.1
   setuptools: 68.0.0
        numpy: 1.26.0
        scipy: 1.11.1
       Cython: None
       pandas: 2.0.3
   matplotlib: 3.7.2
       joblib: 1.2.0
threadpoolctl: 2.2.0

Built with OpenMP: True

threadpoolctl info:
       filepath: C:\Users\mcruz\ztm_ml_projects\sklearn-intro\env\Library\bin\mkl_rt.2.dll
         prefix: mkl_rt
       user_api: blas
   internal_api: mkl
        version: 2023.1-Product
    num_threads: 4
threading_layer: intel

       filepath: C:\Users\mcruz\ztm_ml_projects\sklearn-intro\env\vcomp140.dll
         prefix: vcomp
       user_api: openmp
   internal_api: openmp
        version: None
    num_threads: 8

       filepath: C:\Users\mcruz\ztm_ml_projects\sklearn-intro\env\

<a id='section_3'></a>
### 3. Fit the model/algorithm to training data

In [14]:
from sklearn.model_selection import train_test_split

# split the data into train and test sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [15]:
clf.fit(x_train, y_train)

RandomForestClassifier()

In [16]:
# make a prediction
y_preds = clf.predict(x_test)
y_preds

array([1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1], dtype=int64)

<a id='section_4'></a>

### 4. Evaluating a model

In [17]:
# how well does the model predict?

clf.score(x_train, y_train)

1.0

In [18]:
clf.score(x_test, y_test)

0.9016393442622951

In [19]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(classification_report(y_test, y_preds))

              precision    recall  f1-score   support

           0       0.86      0.86      0.86        22
           1       0.92      0.92      0.92        39

    accuracy                           0.90        61
   macro avg       0.89      0.89      0.89        61
weighted avg       0.90      0.90      0.90        61



In [20]:
confusion_matrix(y_test, y_preds)

array([[19,  3],
       [ 3, 36]], dtype=int64)

In [21]:
accuracy_score(y_test, y_preds)

0.9016393442622951

<a id='section_5'></a>

### 5. Improve a model

In [22]:
# Try differnt amount of n_estimators

np.random.seed(42)

for i in range(10, 100, 10):
    print(f"Trying model with {i} estimators...")
    clf = RandomForestClassifier(n_estimators=i).fit(x_train, y_train)
    print(f"Model accuracy on test set: {clf.score(x_test, y_test) * 100:.2f}%")
    print("")

    

Trying model with 10 estimators...
Model accuracy on test set: 86.89%

Trying model with 20 estimators...
Model accuracy on test set: 88.52%

Trying model with 30 estimators...
Model accuracy on test set: 86.89%

Trying model with 40 estimators...


Model accuracy on test set: 86.89%

Trying model with 50 estimators...
Model accuracy on test set: 90.16%

Trying model with 60 estimators...
Model accuracy on test set: 91.80%

Trying model with 70 estimators...
Model accuracy on test set: 90.16%

Trying model with 80 estimators...
Model accuracy on test set: 90.16%

Trying model with 90 estimators...
Model accuracy on test set: 91.80%



In [23]:
# it looks like n_estimators=40 is best

<a id='section_6'></a>

### 6. Save and load a trained model

In [24]:
import pickle

pickle.dump(clf, open("random_forest_model_1.pkl", "wb"))

In [25]:
loaded_model = pickle.load(open("random_forest_model_1.pkl", "rb"))

loaded_model.score(x_test, y_test)

0.9180327868852459

<a id='section_1'></a>
## 1. Getting Data Ready

Three main things we have to do:
1. Split the data into features and labels (usually `X` & `y`)
2. Filling (also called imputing) or disregarding missing values
3. Converting non-numerical values to numerical values (also called feature encoding)

In [26]:
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [28]:
X = heart_disease.drop("target", axis=1)
y = heart_disease["target"]
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [29]:
# Split the data into training and test sets
# IMPORTANT: never test your model on data it was trained on

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [30]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape


((242, 13), (61, 13), (242,), (61,))

#### Important steps in data handling:
1. Clean data
    - sometimes data is missing or there are outliers
2. Transform data
    - turn non-numerical data into numerical data (feature encoding)
    - feature scaling
3. Reduce data
    - get rid of data that isn't useful or isn't needed


### Transforming data into numbers

In [32]:
car_sales = pd.read_csv("data/car-sales-extended.csv")



Make Colour  Odometer (KM)  Doors  Price
0   Honda  White          35431      4  15323
1     BMW   Blue         192714      5  19943
2   Honda  White          84714      4  28343
3  Toyota  White         154365      4  13434
4  Nissan   Blue         181577      3  14043

In [34]:
# split into x & y
X = car_sales.drop("Price", axis=1)
y = car_sales["Price"]

# training and test split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

#### SKLearn Regressor vs Classifier

- **Regressor:**
  - Used for predicting a number (For example, predicting a house price).
  - Deals with continuous outcomes.

- **Classifier:**
  - Used for predicting whether a sample is one thing or another (For example, whether a tumor is malignant or benign).
  - Deals with categorical outcomes.


In [36]:
# build machine learning model

from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()
# model.fit(X_train, y_train)
# model.score(X_test, y_test)

ValueError: could not convert string to float: 'Toyota'

In [37]:
# convert string to numbers

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

# doors is a categorical feature even though it's a number
# think of it as a category of 3, 4, 5
categorical_features = ["Make", "Colour", "Doors"]

# create an instance of OneHotEncoder
one_hot = OneHotEncoder()

# create an instance of ColumnTransformer
transformer = ColumnTransformer([("one_hot",
                                  one_hot,
                                  categorical_features)],
                                  remainder="passthrough")

# transform the columns with strings to numbers
transformed_X = transformer.fit_transform(X)

transformed_X



array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 3.54310e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        1.00000e+00, 1.92714e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 8.47140e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 6.66040e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.15883e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.48360e+05]])

<img src="./images/one_hot_ex.png"/>


In [38]:
pd.DataFrame(transformed_X)

0    1    2    3    4    5    6    7    8    9    10   11        12
0    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   35431.0
1    1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  192714.0
2    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   84714.0
3    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  154365.0
4    0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  181577.0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...
995  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   35820.0
996  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  155144.0
997  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   66604.0
998  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  215883.0
999  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  248360.0

[1000 rows x 13 columns]

In [39]:
X.head()

Make Colour  Odometer (KM)  Doors
0   Honda  White          35431      4
1     BMW   Blue         192714      5
2   Honda  White          84714      4
3  Toyota  White         154365      4
4  Nissan   Blue         181577      3

In [40]:
dummies = pd.get_dummies(car_sales[["Make", "Colour", "Doors"]])
dummies.head()

Doors  Make_BMW  Make_Honda  Make_Nissan  Make_Toyota  Colour_Black  \
0      4     False        True        False        False         False   
1      5      True       False        False        False         False   
2      4     False        True        False        False         False   
3      4     False       False        False         True         False   
4      3     False       False         True        False         False   

   Colour_Blue  Colour_Green  Colour_Red  Colour_White  
0        False         False       False          True  
1         True         False       False         False  
2        False         False       False          True  
3        False         False       False          True  
4         True         False       False         False

In [41]:
# let's refit the model

np.random.seed(42)

X_train, X_test, y_train, y_test = train_test_split(transformed_X,
                                                    y,
                                                    test_size=0.2)

model.fit(X_train, y_train)

RandomForestRegressor()

In [42]:
model.score(X_test, y_test)

0.3235867221569877